In [1]:
import numpy as np

In [5]:
n=np.array([  [1,2,3,4], [10,20,30,40], [12,13,14,15] ])

In [7]:
n

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40],
       [12, 13, 14, 15]])

In [8]:
n[1:,2:]

array([[30, 40],
       [14, 15]])

# arange

In [10]:
np.arange(5.5,50.3)

array([ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5,
       16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5,
       27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5,
       38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5,
       49.5])

# reshape

In [14]:
a=np.arange(12).reshape(3,4)

In [12]:
np.sqrt(81)

9.0

In [15]:
a.max()

11

In [17]:
a.mean()

5.5

In [24]:
a.argmax()

11

In [25]:
a.argmin()

0

In [26]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [28]:
a+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# Random

In [30]:
np.random.rand(2)

array([0.15492429, 0.21324714])

In [33]:
s=np.random.randint(9,90,12).reshape(6,2)

In [34]:
s.sum()

604

# 3D

In [42]:
d=np.array([[[4,40],[5,50],[6,60]]   , [[7,70],[8,80],[9,90]]  ,  [[5,55],[4,40],[6,60]]  ]  )  

In [43]:
d.shape

(3, 3, 2)

# Nan -not a number

In [45]:
x=np.array([12,56,np.nan,66,100,np.nan])

In [46]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [49]:
x.dtype

dtype('float64')